name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'


    - name: Install Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.3.814'
        clj-kondo: 2022.05.31        # Clj-kondo
        cljfmt: 0.10.2               # cljfmt
        cljstyle: 0.15.0             # cljstyle

    - name: Run Check
      run: make
