name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


artifacts:
  reports:
    junit: junit.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Install Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.3.814'
        clj-kondo: 2022.05.31        # Clj-kondo
        cljfmt: 0.10.2               # cljfmt
        cljstyle: 0.15.0             # cljstyle

    - name: Run Check
      run: make

    - name: Annotate failure
      if: failure()
      uses: mikepenz/action-junit-report@41a3188dde10229782fd78cd72fc574884dd7686
      with:
        report_paths: junit.xml
